const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();const u=tg.initDataUnsafe?.user;if(u)document.getElementById("welcome").textContent=`Привет, ${u.first_name||"пользователь"}`;}
const modal=document.getElementById("modal"),content=document.getElementById("modalContent");function openModal(t,b){content.innerHTML=`<h2>${t}</h2>${b}`;modal.classList.remove("hidden")}function closeModal(){modal.classList.add("hidden")}document.getElementById("closeModal").onclick=closeModal;modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});
const manifestUrl=new URL("./tonconnect-manifest.json",location.href).toString();let connector;
if(window.TON_CONNECT_UI){connector=new TON_CONNECT_UI.TonConnectUI({manifestUrl,buttonRootId:"connectButton"});connector.onStatusChange(async wallet=>{if(!wallet){setDisconnected();return}const a=wallet.account.address;document.getElementById("walletAddress").textContent=short(a);document.getElementById("status").textContent="Кошелёк подключён. Получаем баланс…";await loadBalance(a)})}else document.getElementById("status").textContent="TON Connect не загрузился. Перезагрузите Mini App.";
function short(a){return a.length>18?a.slice(0,8)+"…"+a.slice(-8):a}function setDisconnected(){document.getElementById("walletAddress").textContent="Кошелёк не подключён";document.getElementById("balance").textContent="— TON";document.getElementById("assetTon").textContent="— TON";document.getElementById("status").textContent="Кошелёк не подключён. Нажмите Connect Wallet."}
async function loadBalance(a){try{const r=await fetch("https://toncenter.com/api/v2/getAddressBalance?address="+encodeURIComponent(a));const d=await r.json();if(!d.ok)throw 0;const ton=Number(d.result)/1e9;document.getElementById("balance").textContent=ton.toFixed(4)+" TON";document.getElementById("assetTon").textContent=ton.toFixed(4)+" TON";document.getElementById("status").textContent="Баланс получен из TON blockchain."}catch{document.getElementById("status").textContent="Кошелёк подключён, но баланс не получен. Подключим backend на следующем этапе."}}
document.getElementById("copyBtn").onclick=async()=>{const a=document.getElementById("walletAddress").textContent;if(a==="Кошелёк не подключён")return openModal("Нет кошелька","Сначала подключите TON-кошелёк.");try{await navigator.clipboard.writeText(a);openModal("Готово","Адрес скопирован.")}catch{openModal("Адрес","<p>"+a+"</p>")}};
document.getElementById("receiveBtn").onclick=()=>{const a=document.getElementById("walletAddress").textContent;if(a==="Кошелёк не подключён")return openModal("Получить","Сначала подключите TON-кошелёк.");openModal("Получить TON",`<p>Ваш адрес:</p><div class="note">${a}</div>`)};
document.getElementById("sendBtn").onclick=()=>openModal("Отправить",'<div class="form"><input placeholder="Адрес получателя"><input placeholder="Сумма TON"><button class="primary" onclick="openModal(\'Отправка\',\'<p>Реальную транзакцию подключим следующим этапом через TON Connect.</p>\')">Продолжить</button></div>');
document.getElementById("swapBtn").onclick=()=>openModal("Swap","<p>Swap подключим после настоящего баланса и транзакций.");document.getElementById("swapNav").onclick=()=>document.getElementById("swapBtn").click();document.getElementById("walletBtn").onclick=()=>openModal("Кошелёк","<p>TON Connect подключён. Следующим этапом добавим историю и USDT.</p>");document.getElementById("settingsBtn").onclick=()=>openModal("Настройки",'<p>Настройки добавим позже.</p><p class="danger">Никогда не вводите seed-фразу в Troll.Bank.</p>');